version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: library-postgres
    environment:
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypass123
      POSTGRES_DB: LibraryManagementDB
    ports:
      - "5432:5432"
    volumes:
      - library_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  library_data:
